services:
  - type: web
    name: fashion-review-server
    env: node
    plan: free
    repo: https://github.com/nanailmare/fashion-review-server
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js   # 또는 app.js 등 진입점
    autoDeploy: true