services:
  - type: web
    name: fashion-review-server
    env: node
    plan: free
    repo: https://github.com/nanailmare/fashion-review-server
    branch: main
    rootDir: .
    buildCommand: npm install
    startCommand: node index.js  # 또는 npm start, app.js 등 실제 진입점으로 수정
    autoDeploy: true