services:
  - type: web
    name: fashion-review-server
    env: node
    plan: free
    repo: https://github.com/nanailmare/fashion-review-server
    branch: main
    rootDir: .
    buildCommand: npm install
    startCommand: node index.js   # 또는 실제 진입 파일로 변경
    autoDeploy: true